### ISSUE TITLE
this code that I've got seems more simple, let me show u

### ISSUE THREAD

**Issue by Vinicius-Cerqueira** [oasiscse/URI-Online-Judge-Solve#1]
#include <iostream>

using namespace std;

long long int Fatorial(int n)
{
	if(n==0)
	return 1;
	return n*Fatorial(n-1);
}
int main()
{
	int a,b;
	while(cin >> a >> b)
	{
		cout << Fatorial(a) + Fatorial(b) << endl;		
	}
	
}

**Comment by ihumaunkabir** [comment]
Thanks!  Mention the problem number/ID, please.  Anyway, One problem can be solved in many ways 😄

**Comment by Vinicius-Cerqueira** [comment]
It's the 1161! That's definitely true! ;D
